### ISSUE TITLE
回国模式无法访问谷歌

### ISSUE THREAD

**Issue by jbxiaoyu** [Windelight/SuperACL#1]
我人在国外。怀疑回国模式的规则有些问题，表现为直连可以访问谷歌，添加了自定义规则-》在线规则文件-》inforeign.acl，并选择代理模式为自定义规则后，可以访问百度并显示为国内VPS的IP，但是却无法访问谷歌。

设备为安卓，shadowsocks为最新版

**Comment by Windelight** [comment]
谢谢(*°∀°)=3
第一个Issue诶
正在用我的国外服务器ssclient排查中，请稍等哦

**Comment by Windelight** [comment]
建议你先用降一级的方法试一试，如果你是4.7.1版本的话。
我发现ss-android版本的bug有些问题
https://github.com/shadowsocks/shadowsocks-android/releases
建议使用4.7.0和以下的版本

**Comment by jbxiaoyu** [comment]
谢谢你的回复~~我试着降到了4.7.0的版本，然而发现还是上不去............

并且我还找到了新问题：

我进去youtube，然后界面可以刷新，随便点个视频进去，里面的文字内容（包括影片的封面）都可以加载出来，但是视频却没办法加载（就好像网 非常非常卡的情况一样），会一直转圈圈出不来。

能够判断应该不是我的网的问题，因为我人就在国外，断开SS后 谷歌和youtube都一切正常。

**Comment by Windelight** [comment]
哈喽，我现在下课了
正在准备修复，但是很奇怪刚才尝试一下没有复现，我用的国外Windows服务器，装Shadowsocks，用这个规则可以正常surfing，还可以看YouTube，网速正常
正在尝试构建一个logcat

**Comment by Windelight** [comment]
Sorry仍然没有找到问题所在
服务器上用安卓虚拟机并从Play上下载的最新版Shadowsocks，然后连回国内服务器，网速很正常，我还专门看了YouTube 4K也是正常的。
我检查了文件格式，然后又调日志，接着又debug，并且确认这个回国版里面没有那些贪婪匹配的正则表达式
明天(应该是今天啦)我会继续弄啦，因为我是国内的，所以暂时没有漫游电话卡和国外手机，无法进行真机测试，抱歉了
如果今天看到的话，请帮我测试一下单表，也就是将github raw链接内容双击全选复制到ss，然后按从剪贴板导入，再测试一下，谢谢了
(*•̀ᴗ•́*)و ̑̑

**Comment by Windelight** [comment]
我觉得这个文件应该不是问题，大陆这头的任何服务都不可能访问谷歌，而你的网络可以，并且这个规则没有性能问题，但是你又上的了谷歌，所以如果可以的话希望帮助提供一下机器型号，ss提供商，以及从谷歌上搜ip，或者ip.cn，ip.cn这个域名没有加，也不会加。另外请一定要确认列表里有且只有 https://raw.githubusercontent.com/Windelight/SuperACL/master/inforeign.acl

**Comment by jbxiaoyu** [comment]
非常感谢你的回复！！你上述实验我都做了，一切正常。

而且我还有另外一个在美国的VPS（我不在美国），结果发现也都一切正常。
即：【美国VPS+全局】上谷歌显示的是美国谷歌界面，即上谷歌走VPS；
而 【美国VPS+自定义规则】上谷歌显示为本地谷歌界面，即上谷歌直连；

因此可以推断，应该是我国内VPS的问题。

我的手机是小米5S，国内的VPS提供商叫VPS大师（http://www.vpssir.com/），我选用的是NAT类型的国内VPS（因为很便宜.......一个月20块RMB）。所以会不会跟这有关呢？但是照理说这些规则不应该是在手机SS客户端就处理了吗？一旦发现是列表以外的网站，就根本不会向VPS发送请求呀？（不知道我理解的对不对）

所以，就很奇怪...........不过不管怎么说，还是很谢谢你！！你这个项目很不错，因为我在网上都只能找到翻墙出去的PAC规则，关于翻回来的很少很少。所以我很支持你！

**Comment by Windelight** [comment]
我认为这个问题好牛啊，我是小米MCE8，MIUI10中国大陆版最新版，我用这个规则在测试inforeign.acl，百度搜到的是我的国外服务器ip，而谷歌不能访问（￣□￣；）  
用IPIP是这样的  
![Screenshot_2019-02-23-14-47-04-852_com.android.browser.png](https://i.loli.net/2019/02/23/5c70ecda5dcb0.png)  
反过来Speedtest是这样的
![Screenshot_2019-02-23-14-46-58-198_com.android.browser.png](https://i.loli.net/2019/02/23/5c70ed108d3cc.png)

**Comment by Windelight** [comment]
对了٩( •̀㉨•́ )و !
如果是你的相对比较坑爹的服务器，我建一下我的shadowsocks回国机，地址是
`ss://eGNoYWNoYTIwLWlldGYtcG9seTEzMDU6TkNZc2hhZG93c29ja3M3NTM5NTE@ncy-tianjin-14113765.publicdns.nciyuan.net:51667#NciYuan!%20FreeInternal%20VPN`
### 河北省天津市的服务器！！！
**(小声比比)**
然后的话请试一下谷歌相对的速度，以及这个BGP的话看看翻回国内的速度
有效期随缘啦😄
┗(＾0＾)┓

**Comment by jbxiaoyu** [comment]
好的，国内服务器我还暂时用不到，我原来这个就用得还不错，不过还是要谢谢你~~

**Comment by Windelight** [comment]
那么请问可以试试吗？
还有想征询一下您在当地的谷歌访问速度
另外排除或确认到底是不是服务器的问题

**Comment by jbxiaoyu** [comment]
我本身的网络不管是连接google还是youtube都是秒连，就几乎没有什么延迟就打开了。看1080P什么的都完全无压力。

然后刚刚试了一下你的这个SS（你应该是用腾讯云搭的），然后就跟我那个回国的SS基本一模一样的症状.........就很奇怪........

**Comment by Windelight** [comment]
太谢谢你了(*°∀°)=3，我定位到了问题

**Comment by Windelight** [comment]
我想请问一下你现在是不是在港府？
我这边看到shadowsocks服务端日志里面有两个ip，一个是 221.192.180.68，查了一下AS是4837，属于China Unicom CHN-169 Backbone，也就是河北联通。然后呢另外一个是 61.238.92.52，查了一下AS是9269，属于Hong Kong Broadband Network Ltd.也就是香港宽频，但是RTBAsia的数据是香港城市电讯。不管怎么说，日志体现了问题所在。
你用的应该是你的运营商提供的DNS，那么谷歌除了大陆朝鲜之外都是有

**Comment by Windelight** [comment]
IPv6的，但是过没有呢，所以你一旦给服务器发送IPv6数据包，那么服务端就报
[Errno 99] Cannot assign requested address
简单来说就是不知道这是啥包，直接丢掉
另外就是你在用远程DNS的时候设置成了8.8.8.8，然后呢？这玩意除了中国大陆加朝鲜以及古巴伊朗和非洲大陆，其它地方特好使！！！！所以服务端报
[Errno 104] Connection reset by peer
也就是说你被GFW随机丢包了，并且这个DNS在大陆地区平均速度都是几百ms，再传回你的手机，那更慢了。

**Comment by Windelight** [comment]
而且DNS的标准端口数据包也被GFW卡得基本上没剩几个了
下图
![Screenshot_2019-02-23-19-00-33-759_com.sonelli.juicessh.png](https://i.loli.net/2019/02/23/5c712865eabb8.png)
所以说首先建议你在ss-android的配置文件里面把DNS改成223.5.5.5，这个是阿里DNS，然后呢IPv6就基本没戏了。想关闭的话，如果是手机流量可以从APN里把IPv6关掉，WiFi的话可以把网卡的IPv6协议或者进入路由器管理界面关掉IPv6。
不过呢由于我是云玩家，我的手机卡可以用IPv6，并且有概率直接访问谷歌，家里宽带不行，学校的可以，国内服务器只有IPv4，而我的翻墙服务器有IPv6，所以很抱歉我不能保证关掉IPv6这种能成，但是希望你试一下哦

**Comment by Windelight** [comment]
我比较倾向于认为这样的，对了也要提一下服务商除了看到IP时间和域名，看不到你的数据啦|｡･㉨･)っ
这个是我测试时候一切正常的代理
![Screenshot_2019-02-23-19-13-21-089_com.sonelli.juicessh.png](https://i.loli.net/2019/02/23/5c712b78f3e54.png)
![Screenshot_2019-02-23-19-13-29-452_com.sonelli.juicessh.png](https://i.loli.net/2019/02/23/5c712b927d862.png)
看看是否很OK?
然后...........................
![Screenshot_2019-02-23-19-14-09-078_com.sonelli.juicessh.png](https://i.loli.net/2019/02/23/5c712bec2ced6.png)
![Screenshot_2019-02-23-19-14-20-731_com.sonelli.juicessh.png](https://i.loli.net/2019/02/23/5c712bec4bb29.png)
这就是为什么谷歌速度很慢的原因了，因为大约90%四个八DNS请求全部宕掉了，而你的客户端把请求转到这里时，GFW直接把你阻断了。
目前GFW只是具有初步的特征识别，但是无法破译。但是数据到了服务器，服务器再去访问4个8，那就被宕掉了。(´-㉨ก`)

**Comment by Windelight** [comment]
当然我仍然不排除一种可能性是，我的服务器在访问你的HKBN地址时，你被GFW给墙掉了，就是我的这个服务器往外连接，了然后连接你的IP，经过广州出口时，GFW认为你是个代理机，就给Block或者随机丢包了

**Comment by Windelight** [comment]
Edit: 我先给我的服务器Shutdown了，如果要是仍然无法解决问题，你再在Github跟进，继续进行分析了 ( ¯•㉨•¯ )

**Comment by Windelight** [comment]
Edit:我先给我的服务器 Shutdown了，如果要是仍然无法解决问题，你再在 Github跟进哦  (¯•㉨•¯)

**Comment by jbxiaoyu** [comment]
感谢你的帮助，试过更改DNS为223.5.5.5，完全无法连接网络........

但其实后来我才意识到其实有个选项是“分应用VPN”..................所以其实在手机上面只要把那些想要翻回来的APP加进去就可以了（比如网易云音乐，爱奇艺呀之类的），这样其实google，youtube什么的完全就不用担心了。

另外关于电脑版的SS，我自己其实有编了一份回国白名单的PAC规则，所以倒是完全够用啦~

不管怎么说，还是很感谢你的帮助！！！

**Comment by Windelight** [comment]
好的，解决问题就是最好了
另外那会忘了国内DNS是被投毒的，所以解析是不可能的
IPv6的问题我看国内云服基本没辙🤔
希望你继续支持我的项目，如有需要请帮助推荐给更多的人哦😄
