### ISSUE TITLE
白名单模式

### ISSUE THREAD

**Issue by updater1234** [Windelight/SuperACL#2]
请问，能添加一种白名单模式吗？就是说，所有国内ip直连，国外ip走代理。毕竟国外访问缓慢的网站太多了，如果采用这种方式的话，我觉得效率会高很多毕竟只用更新国内ip段就行了。

**Comment by Windelight** [comment]
白名单模式？好主意(✪▽✪)！

**Comment by Windelight** [comment]
这个如果说IP地址的话IANA的数据库和ICANN的数据库里有完整的AS和对应IP网段的数据，ICANN有十分详尽的中国AS域的大陆地区IP，不过目前为了兼容Shadowsocks-Android和Shadowsocks-rss-Android 暂时只能用代理bypass-all加proxy-list

**Comment by Windelight** [comment]
而且ss-android只支持bypass-all加proxy-list
那就是只能身在国外的回家专用吧

**Comment by updater1234** [comment]
额，如果是这样的话，那对于国内科学上网就没什么太大意义了。

**Comment by Windelight** [comment]
请问你是ss用户还是ssr用户？我觉得可以做一份

**Comment by updater1234** [comment]
我是ss用户

**Comment by Windelight** [comment]
ss-android的话他只能选择proxy，然后其它bypass，如果你在国内的话，这个ss国内翻出去的用户是无法使用的，如果ok的话推荐用ssr-或者ssrr-android。breakwa11大神的shadowsocks-rss向下兼容原版shadowsocks，所以只要填入原来的信息，协议origin，内容无，混淆plain，内容无就可以了

**Comment by updater1234** [comment]
但这前提是ss没有开plugin,可我的ss是开了v2ray-plugin所以shadowsocks-rss就不管用啦。

**Comment by updater1234** [comment]
除非等shadowsocks官方那边支持，我觉得这个白名单模式的plan大可不必这么急。

**Comment by updater1234** [comment]
刚才在shadowsocks-libev的tree上找到一个中国IP段直连的acl:https://github.com/shadowsocks/shadowsocks-libev/blob/master/acl/chn.acl，不过这个文件已经是3年前的了，不知还有没有参考价值。

**Comment by Windelight** [comment]
实际上来说现在GFW的封锁能力不断提高，而Shadowsocks最开始的Python版本的第一作者已经被喝茶了，所以本身基本停滞了开发。Shadowsocks-Android目前有正常更新，Shadowsocks-rss服务端的作者也因为某些原因的问题停止开发，顺带Shadowsocks-RSS-Android已经很长时间没有更新，以后也就是很少量的更新，而现在客户端有一个第三方维护的Shadowsocks-RR-Android。

**Comment by Windelight** [comment]
ss-android支持的加密协议多，速度相对比较快，ACL比较残废但是每次连接就会及时更新。
ssr-android和ssrr支持的加密很少，倒是可以混淆，据说可以更难检测，顺便可以免流。ACL语法支持比较好，但是你必须得手动更新。但还有一点这个向下兼容，其它的没什么两样。手机端的Shadowsocks系列软件都是用ACL，电脑端系列软件大多数都是用PAC

**Comment by updater1234** [comment]
如果我刚才找到的acl文件还有参考价值的话，你可以尝试做一下。
